import type { Metadata } from 'next'
import Image from 'next/image'
// const inter = Inter({ subsets: ['latin'] })
import './globals.css'
// import Navbar from '../components/Navbar'
// import Footer from '../components/Footer'
import NewNavbar from './components-new/Navbar'
export const metadata: Metadata = {
  title: 'Car Hub',
  description: 'Generated by create next app',
}
import  Header  from './home2/components/Header'
import { ChakraProvider } from '@chakra-ui/react'
import store from '../store'
import { Toaster } from '@/components/ui/toaster'
import { Provider } from 'react-redux'
import { Suspense } from 'react'
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="relative flex flex-col overflow-x-hidden bg-gray-200">
        {/* This adds a background image */}
        {/* <div className="absolute w-full h-dvh -z-10">
      
        <Image
          src="/sky-background-largeScreen.jpg"
          alt="Background Image"
          layout="fill"
        />
      </div> */}
        <ChakraProvider>
          {/* <NextAuthProvider> */}
          {/* <Navbar /> */}
          
          <Suspense>
            <Header />
          </Suspense>
          {children}

          {/* <Footer /> */}
          {/* </NextAuthProvider> */}
        </ChakraProvider>
        <Toaster />
      </body>
    </html>
  )
}
