import { OptionType } from "../app/home2/interfaces/WeatherCardInterfaces";


export const  items: OptionType[] = [
    { label: "Tokyo", value: "1" },
    { label: "Delhi", value: "2" },
    { label: "Shanghai", value: "3" },
    { label: "São Paulo", value: "4" },
    { label: "Mumbai", value: "5" },
    { label: "Mexico City", value: "6" },
    { label: "Beijing", value: "7" },
    { label: "Osaka", value: "8" },
    { label: "Cairo", value: "9" },
    { label: "New York", value: "10" },
    { label: "Dhaka", value: "11" },
    { label: "Karachi", value: "12" },
    { label: "Buenos Aires", value: "13" },
    { label: "Kolkata", value: "14" },
    { label: "Istanbul", value: "15" },
    { label: "Chongqing", value: "16" },
    { label: "Lagos", value: "17" },
    { label: "Manila", value: "18" },
    { label: "Rio de Janeiro", value: "19" },
    { label: "Guangzhou", value: "20" },
    { label: "Los Angeles", value: "21" },
    { label: "Moscow", value: "22" },
    { label: "Kinshasa", value: "23" },
    { label: "Tianjin", value: "24" },
    { label: "Paris", value: "25" },
    { label: "Lima", value: "26" },
    { label: "Bangkok", value: "27" },
    { label: "London", value: "28" },
    { label: "Chengdu", value: "29" },
    { label: "Nairobi", value: "30" },
    { label: "Lahore", value: "31" },
    { label: "Bangalore", value: "32" },
    { label: "Seoul", value: "33" },
    { label: "Bogotá", value: "34" },
    { label: "Nagoya", value: "35" },
    { label: "Riyadh", value: "36" },
    { label: "Ho Chi Minh City", value: "37" },
    { label: "Wuhan", value: "38" },
    { label: "Hong Kong", value: "39" },
    { label: "Ahmedabad", value: "40" },
    { label: "Baghdad", value: "41" },
    { label: "Hyderabad", value: "42" },
    { label: "Houston", value: "43" },
    { label: "Atlanta", value: "44" },
    { label: "Toronto", value: "45" },
    { label: "Kuala Lumpur", value: "46" },
    { label: "Santiago", value: "47" },
    { label: "Madrid", value: "48" },
    { label: "Dallas", value: "49" },
    { label: "Singapore", value: "50" },
    { label: "Philadelphia", value: "51" },
    { label: "Miami", value: "52" },
    { label: "Milan", value: "53" },
    { label: "Jakarta", value: "54" },
    { label: "Chicago", value: "55" },
    { label: "Sydney", value: "56" },
    { label: "Berlin", value: "57" },
    { label: "Barcelona", value: "58" },
    { label: "San Francisco", value: "59" },
    { label: "Melbourne", value: "60" },
    { label: "Dubai", value: "61" },
    { label: "Munich", value: "62" },
    { label: "Rome", value: "63" },
    { label: "Kyoto", value: "64" },
    { label: "Lisbon", value: "65" },
    { label: "Vienna", value: "66" },
    { label: "Brussels", value: "67" },
    { label: "Manhattan", value: "68" },
    { label: "Amsterdam", value: "69" },
    { label: "Istanbul", value: "70" },
    { label: "Warsaw", value: "71" },
    { label: "Budapest", value: "72" },
    { label: "Copenhagen", value: "73" },
    { label: "Helsinki", value: "74" },
    { label: "Stockholm", value: "75" },
    { label: "Oslo", value: "76" },
    { label: "Dublin", value: "77" },
    { label: "Geneva", value: "78" },
    { label: "Zurich", value: "79" },
    { label: "Prague", value: "80" },
    { label: "Hamburg", value: "81" },
    { label: "Frankfurt", value: "82" },
    { label: "Bratislava", value: "83" },
    { label: "Luxembourg", value: "84" },
    { label: "Ljubljana", value: "85" },
    { label: "Riga", value: "86" },
    { label: "Tallinn", value: "87" },
    { label: "Vilnius", value: "88" },
    { label: "Zagreb", value: "89" },
    { label: "Sarajevo", value: "90" },
    { label: "Skopje", value: "91" },
    { label: "Belgrade", value: "92" },
    { label: "Podgorica", value: "93" },
    { label: "Pristina", value: "94" },
    { label: "Sofia", value: "95" },
    { label: "Bucharest", value: "96" },
    { label: "Athens", value: "97" },
    { label: "Nicosia", value: "98" },
    { label: "Ankara", value: "99" },
    { label: "Addis Ababa", value: "100" },
    { label: "Harare", value: "101" },
    { label: "Lusaka", value: "102" },
    { label: "Gaborone", value: "103" },
    { label: "Windhoek", value: "104" },
    { label: "Luanda", value: "105" },
    { label: "Kampala", value: "106" },
    { label: "Dar es Salaam", value: "107" },
    { label: "Maputo", value: "108" },
    { label: "Lilongwe", value: "109" },
    { label: "Kigali", value: "110" },
    { label: "Bujumbura", value: "111" },
    { label: "Juba", value: "112" },
    { label: "Khartoum", value: "113" },
    { label: "Algiers", value: "114" },
    { label: "Tunis", value: "115" },
    { label: "Rabat", value: "116" },
    { label: "Tripoli", value: "117" },
    { label: "Nouakchott", value: "118" },
    { label: "Bamako", value: "119" },
    { label: "Ouagadougou", value: "120" },
    { label: "Niamey", value: "121" },
    { label: "Dakar", value: "122" },
    { label: "Conakry", value: "123" },
    { label: "Bissau", value: "124" },
    { label: "Freetown", value: "125" },
    { label: "Monrovia", value: "126" },
    { label: "Abidjan", value: "127" },
    { label: "Accra", value: "128" },
    { label: "Lomé", value: "129" },
    { label: "Cotonou", value: "130" },
    { label: "Porto-Novo", value: "131" },
    { label: "Yaoundé", value: "132" },
    { label: "Libreville", value: "133" },
    { label: "Brazzaville", value: "134" },
    { label: "Kinshasa", value: "135" },
    { label: "Bangui", value: "136" },
    { label: "N'Djamena", value: "137" },
    { label: "Niamey", value: "138" },
    { label: "Addis Ababa", value: "139" },
    { label: "Mogadishu", value: "140" },
    { label: "Djibouti", value: "141" },
    { label: "Asmara", value: "142" },
    { label: "Nairobi", value: "143" },
    { label: "Kampala", value: "144" },
    { label: "Dar es Salaam", value: "145" },
    { label: "Maputo", value: "146" },
    { label: "Antananarivo", value: "147" },
    { label: "Port Louis", value: "148" },
    { label: "Saint-Denis", value: "149" },
    { label: "Mamoudzou", value: "150" },
    { label: "Victoria", value: "151" },
    { label: "Cape Town", value: "152" },
    { label: "Pretoria", value: "153" },
    { label: "Bloemfontein", value: "154" },
    { label: "Windhoek", value: "155" },
    { label: "Gaborone", value: "156" },
    { label: "Maseru", value: "157" },
    { label: "Mbabane", value: "158" },
    { label: "Harare", value: "159" },
    { label: "Lusaka", value: "160" },
    { label: "Lilongwe", value: "161" },
    { label: "Brazzaville", value: "162" },
    { label: "Libreville", value: "163" },
    { label: "São Tomé", value: "164" },
    { label: "Malabo", value: "165" },
    { label: "Yaoundé", value: "166" },
    { label: "N'Djamena", value: "167" },
    { label: "Bangui", value: "168" },
    { label: "Luanda", value: "169" },
    { label: "Kinshasa", value: "170" },
    { label: "Brazzaville", value: "171" },
    { label: "Libreville", value: "172" },
    { label: "Malabo", value: "173" },
    { label: "Banjul", value: "174" },
    { label: "Bissau", value: "175" },
    { label: "Praia", value: "176" },
    { label: "Accra", value: "177" },
    { label: "Lomé", value: "178" },
    { label: "Cotonou", value: "179" },
    { label: "Porto-Novo", value: "180" },
    { label: "Abuja", value: "181" },
    { label: "Lagos", value: "182" },
    { label: "Monrovia", value: "183" },
    { label: "Freetown", value: "184" },
    { label: "Conakry", value: "185" },
    { label: "Dakar", value: "186" },
    { label: "Banjul", value: "187" },
    { label: "Nouakchott", value: "188" },
    { label: "Bamako", value: "189" },
    { label: "Ouagadougou", value: "190" },
    { label: "Niamey", value: "191" },
    { label: "Algiers", value: "192" },
    { label: "Tunis", value: "193" },
    { label: "Rabat", value: "194" },
    { label: "Cairo", value: "195" },
    { label: "Khartoum", value: "196" },
    { label: "Asmara", value: "197" },
    { label: "Djibouti", value: "198" },
    { label: "Mogadishu", value: "199" },
    { label: "Addis Ababa", value: "200" },
    { label: "Nairobi", value: "201" },
    { label: "Kampala", value: "202" },
    { label: "Dar es Salaam", value: "203" },
    { label: "Bujumbura", value: "204" },
    { label: "Kigali", value: "205" },
    { label: "Maputo", value: "206" },
    { label: "Antananarivo", value: "207" },
    { label: "Port Louis", value: "208" },
    { label: "Victoria", value: "209" },
    { label: "Moroni", value: "210" },
    { label: "Dodoma", value: "211" },
    { label: "Lilongwe", value: "212" },
    { label: "Lusaka", value: "213" },
    { label: "Harare", value: "214" },
    { label: "Windhoek", value: "215" },
    { label: "Gaborone", value: "216" },
    { label: "Maseru", value: "217" },
    { label: "Mbabane", value: "218" },
    { label: "Bloemfontein", value: "219" },
    { label: "Pretoria", value: "220" },
    { label: "Cape Town", value: "221" },
    { label: "Bogotá", value: "222" },
    { label: "Lima", value: "223" },
    { label: "Quito", value: "224" },
    { label: "Caracas", value: "225" },
    { label: "Buenos Aires", value: "226" },
    { label: "Montevideo", value: "227" },
    { label: "Brasília", value: "228" },
    { label: "Santiago", value: "229" },
    { label: "Asunción", value: "230" },
    { label: "Sucre", value: "231" },
    { label: "La Paz", value: "232" },
    { label: "Paramaribo", value: "233" },
    { label: "Georgetown", value: "234" },
    { label: "San José", value: "235" },
    { label: "Panama City", value: "236" },
    { label: "Belmopan", value: "237" },
    { label: "Tegucigalpa", value: "238" },
    { label: "San Salvador", value: "239" },
    { label: "Managua", value: "240" },
    { label: "Guatemala City", value: "241" },
    { label: "Mexico City", value: "242" },
    { label: "Havana", value: "243" },
    { label: "Kingston", value: "244" },
    { label: "Santo Domingo", value: "245" },
    { label: "Port-au-Prince", value: "246" },
    { label: "Nassau", value: "247" },
    { label: "Bridgetown", value: "248" },
    { label: "Castries", value: "249" },
    { label: "Kingstown", value: "250" },
    { label: "St. George's", value: "251" },
    { label: "Roseau", value: "252" },
    { label: "Basseterre", value: "253" },
    { label: "Basse-Terre", value: "254" },
    { label: "Fort-de-France", value: "255" },
    { label: "Philipsburg", value: "256" },
    { label: "Marigot", value: "257" },
    { label: "Gustavia", value: "258" },
    { label: "San Juan", value: "259" },
    { label: "Charlotte Amalie", value: "260" },
    { label: "Oranjestad", value: "261" },
    { label: "Willemstad", value: "262" },
    { label: "Kralendijk", value: "263" },
    { label: "The Valley", value: "264" },
    { label: "Road Town", value: "265" },
    { label: "Plymouth", value: "266" },
    { label: "Brades", value: "267" },
    { label: "St. John's", value: "268" },
    { label: "Madrid", value: "269" },
    { label: "Barcelona", value: "270" },
    { label: "Lisbon", value: "271" },
    { label: "Porto", value: "272" },
    { label: "Paris", value: "273" },
    { label: "Marseille", value: "274" },
    { label: "Lyon", value: "275" },
    { label: "Toulouse", value: "276" },
    { label: "Nice", value: "277" },
    { label: "Bordeaux", value: "278" },
    { label: "Berlin", value: "279" },
    { label: "Hamburg", value: "280" },
    { label: "Munich", value: "281" },
    { label: "Cologne", value: "282" },
    { label: "Frankfurt", value: "283" },
    { label: "Stuttgart", value: "284" },
    { label: "Düsseldorf", value: "285" },
    { label: "Dortmund", value: "286" },
    { label: "Essen", value: "287" },
    { label: "Leipzig", value: "288" },
    { label: "Bremen", value: "289" },
    { label: "Dresden", value: "290" },
    { label: "Hannover", value: "291" },
    { label: "Nuremberg", value: "292" },
    { label: "Duisburg", value: "293" },
    { label: "Bochum", value: "294" },
    { label: "Wuppertal", value: "295" },
    { label: "Bielefeld", value: "296" },
    { label: "Bonn", value: "297" },
    { label: "Münster", value: "298" },
    { label: "Karlsruhe", value: "299" },
    { label: "Mannheim", value: "300" },
    { label: "Augsburg", value: "301" },
    { label: "Wiesbaden", value: "302" },
    { label: "Gelsenkirchen", value: "303" },
    { label: "Mönchengladbach", value: "304" },
    { label: "Braunschweig", value: "305" },
    { label: "Chemnitz", value: "306" },
    { label: "Kiel", value: "307" },
    { label: "Aachen", value: "308" },
    { label: "Halle (Saale)", value: "309" },
    { label: "Magdeburg", value: "310" },
    { label: "Freiburg", value: "311" },
    { label: "Krefeld", value: "312" },
    { label: "Lübeck", value: "313" },
    { label: "Oberhausen", value: "314" },
    { label: "Erfurt", value: "315" },
    { label: "Mainz", value: "316" },
    { label: "Rostock", value: "317" },
    { label: "Kassel", value: "318" },
    { label: "Hagen", value: "319" },
    { label: "Hamm", value: "320" },
    { label: "Saarbrücken", value: "321" },
    { label: "Mülheim", value: "322" },
    { label: "Potsdam", value: "323" },
    { label: "Ludwigshafen", value: "324" },
    { label: "Oldenburg", value: "325" },
    { label: "Leverkusen", value: "326" },
    { label: "Osnabrück", value: "327" },
    { label: "Solingen", value: "328" },
    { label: "Herne", value: "329" },
    { label: "Neuss", value: "330" },
    { label: "Regensburg", value: "331" },
    { label: "Paderborn", value: "332" },
    { label: "Ingolstadt", value: "333" },
    { label: "Würzburg", value: "334" },
    { label: "Wolfsburg", value: "335" },
    { label: "Offenbach", value: "336" },
    { label: "Ulm", value: "337" },
    { label: "Heilbronn", value: "338" },
    { label: "Pforzheim", value: "339" },
    { label: "Göttingen", value: "340" },
    { label: "Bottrop", value: "341" },
    { label: "Trier", value: "342" },
    { label: "Recklinghausen", value: "343" },
    { label: "Reutlingen", value: "344" },
    { label: "Bremerhaven", value: "345" },
    { label: "Koblenz", value: "346" },
    { label: "Bergisch Gladbach", value: "347" },
    { label: "Jena", value: "348" },
    { label: "Remscheid", value: "349" },
    { label: "Erlangen", value: "350" },
    { label: "Moers", value: "351" },
    { label: "Siegen", value: "352" },
    { label: "Hildesheim", value: "353" },
    { label: "Cottbus", value: "354" },
    { label: "Gera", value: "355" },
    { label: "Witten", value: "356" },
    { label: "Zwickau", value: "357" },
    { label: "Essen", value: "358" },
    { label: "Mülheim an der Ruhr", value: "359" },
    { label: "Bergkamen", value: "360" },
    { label: "Castrop-Rauxel", value: "361" },
    { label: "Gladbeck", value: "362" },
    { label: "Dorsten", value: "363" },
    { label: "Velbert", value: "364" },
    { label: "Marl", value: "365" },
    { label: "Bottrop", value: "366" },
    { label: "Remscheid", value: "367" },
    { label: "Herten", value: "368" },
    { label: "Recklinghausen", value: "369" },
    { label: "Herne", value: "370" },
    { label: "Gelsenkirchen", value: "371" },
    { label: "Bochum", value: "372" },
    { label: "Oberhausen", value: "373" },
    { label: "Mülheim an der Ruhr", value: "374" },
    { label: "Duisburg", value: "375" },
    { label: "Essen", value: "376" },
    { label: "Dortmund", value: "377" },
    { label: "Hagen", value: "378" },
    { label: "Hamm", value: "379" },
    { label: "Münster", value: "380" }
]